variables:
  LANG: en_US.UTF-8
  LC_ALL: en_US.UTF-8
  ###########################################

stages:
  - tests
  - build_and_upload
  - refresh_dsym
  ###########################################

before_script:
  - if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi
  - gem install bundler
  - bundle install
  ###########################################

# Unit & UI Test on Staging
tests:
  dependencies: []
  stage: tests
  artifacts:
    name: "reports_${CI_PROJECT_NAME}_${CI_BUILD_REF_NAME}_${CI_JOB_NAME}_${CI_JOB_ID}"
    when: always
    paths:
      - fastlane/tests
  script:
    - bundle exec fastlane test production:false
  tags:
    - <RUNNER_TAG>
  only:
    - /^release-.*$/
    - master
    - dev
    - merge_request
  ###########################################

# STAGING STEPS

build_staging:
  dependencies: []
  stage: build_and_upload
  script:
    - bundle exec fastlane build_with_upload production:false
  tags:
    - <RUNNER_TAG>
  retry: 1
  only:
    - dev
  when: on_success
  allow_failure: false
  ###########################################

dsym_staging:
  dependencies: []
  stage: refresh_dsym
  script:
    - bundle exec fastlane refresh_dsym production:false
  tags:
    - <RUNNER_TAG>
  retry: 2
  only:
    - dev
  when: on_success
  ###########################################


# PRODUCTION STEPS

build_prod:
  dependencies: []
  stage: build_and_upload
  script:
    - bundle exec fastlane build_with_upload production:true
  tags:
    - <RUNNER_TAG>
  retry: 1
  only:
    - /^release-.*$/
    - master
  when: on_success
  allow_failure: false
  ###########################################

dsym_prod:
  dependencies: []
  stage: refresh_dsym
  script:
    - bundle exec fastlane refresh_dsym production:true
  tags:
    - <RUNNER_TAG>
  retry: 2
  only:
    - /^release-.*$/
    - master
  when: on_success
  ###########################################

